---
# tasks file for go_collect_log
- name: push builed file
  copy:
    src: "{{src_path}}"
    dest: "{{dest_path}}"
    owner: root
    group: root
    mode: 777    
- name: Copy systemd service file to server
  copy:
    src: go_collect_log.service
    dest: /etc/systemd/system
    owner: root
    group: root
  notify:
    - Start service    